/** User-facing copy for SessionActivity (SPEC-055 §5). */
export const SessionActivityStrings = {
  set: 'Set',
  values: 'Values',
  any: 'Any',
  separate: 'Separate',
  summed: 'Summed',
  add: 'Add',
  firstAvailableGroup: 'First available group',
  unassigned: 'Unassigned',
  sessionSections: 'Session sections',
  inviteLinkQrCode: 'Invite link QR code',
  encounterTemplate: 'Encounter Template',
  remove: 'Remove',
  eGAttackRoll: 'e.g. Attack roll',
  modeFreeLabel: 'Free',
  modeFreeHint: 'The app tracks nothing — no order, no rounds, no tracker. Call for rolls yourself; players use the Roll sheet. Any rules system.',
  modeSideLabel: 'Side-based',
  modeSideHint: 'One initiative row per active group. Uses the Initiative die on the encounter profile.',
  modeIndividualLabel: 'Individual',
  modeIndividualHint: "One initiative row per active token. Uses the Initiative die on each player's profile.",
  gridTooSmall: 'Grid must be at least 1×1 cells.',
  removeSeatsFailed: 'Failed to remove seats',
  pruneFailed: 'Prune failed',
  deleteRoomFailed: 'Failed to delete room',
} as const;
